Instructions:

What is the number of distinct countries present in the database? The output should be single column aliased with the following name: total_distinct_countries.

What are the distinct debt indicators? The output column should be aliased as distinct_debt_indicators and the outputs should be ordered by it.

What is the total amount of debt owed by all the countries present in the table, in millions, rounded to two decimals? The output should be single column aliased with the following name: total_debt.

What country has the highest amount of debt? Your output should contain two columns: country_name and total_debt.

What is the average amount of debt across different debt indicators? The output table should contain debt_indicator, indicator_name, and average_debt.

What country has the highest amount of principal repayments in the "DT.AMT.DLXF.CD" category? The output table should contain two columns: country_name and indicator_name.

In [83]:
SELECT count(DISTINCT country_name) as total_distinct_countries
FROM public.international_debt;

   total_distinct_countries
0                       124

In [84]:
SELECT DISTINCT indicator_name as distinct_debt_indicators
FROM public.international_debt;

                             distinct_debt_indicators
0   Principal repayments on external debt, private...
1                       PPG, bonds (INT, current US$)
2   Interest payments on external debt, long-term ...
3                PPG, multilateral (INT, current US$)
4            PPG, commercial banks (AMT, current US$)
5          PPG, official creditors (AMT, current US$)
6                       PPG, bonds (AMT, current US$)
7   Interest payments on external debt, private no...
8                   PPG, bilateral (AMT, current US$)
9           PPG, private creditors (INT, current US$)
10    PPG, other private creditors (DIS, current US$)
11         PPG, official creditors (INT, current US$)
12  Disbursements on external debt, long-term (DIS...
13               PPG, multilateral (DIS, current US$)
14                  PPG, bilateral (INT, current US$)
15         PPG, official creditors (DIS, current US$)
16  Principal repayments on external debt, long-te...
17                  PPG, bilateral (DIS, current US$)
18          PPG, private creditors (AMT, current US$)
19           PPG, commercial banks (DIS, current US$)
20    PPG, other private creditors (INT, current US$)
21               PPG, multilateral (AMT, current US$)
22           PPG, commercial banks (INT, current US$)
23          PPG, private creditors (DIS, current US$)
24    PPG, other private creditors (AMT, current US$)

In [85]:
SELECT ROUND((sum(debt) / 1000000), 2) as total_debt
FROM public.international_debt;

   total_debt
0  3079734.49

In [86]:
SELECT country_name, sum(debt) as total_debt FROM international_debt
GROUP BY country_name
ORDER BY total_debt DESC
LIMIT 1;

  country_name    total_debt
0        China  2.857935e+11

In [87]:
SELECT indicator_code as debt_indicator,
		indicator_name,
		avg(debt) as average_debt
	FROM international_debt 
	GROUP BY indicator_code, indicator_name
	ORDER BY average_debt DESC
	LIMIT 10;

   debt_indicator  ...  average_debt
0  DT.AMT.DLXF.CD  ...  5.904868e+09
1  DT.AMT.DPNG.CD  ...  5.161194e+09
2  DT.DIS.DLXF.CD  ...  2.152041e+09
3  DT.DIS.OFFT.CD  ...  1.958983e+09
4  DT.AMT.PRVT.CD  ...  1.803694e+09
5  DT.INT.DLXF.CD  ...  1.644024e+09
6  DT.DIS.BLAT.CD  ...  1.223139e+09
7  DT.INT.DPNG.CD  ...  1.220411e+09
8  DT.AMT.OFFT.CD  ...  1.191188e+09
9  DT.AMT.PBND.CD  ...  1.082624e+09

[10 rows x 3 columns]

In [88]:
SELECT country_name, indicator_name
	FROM international_debt
	WHERE indicator_code = 'DT.AMT.DLXF.CD'
	ORDER BY international_debt.debt DESC
	LIMIT 1;

  country_name                                     indicator_name
0        China  Principal repayments on external debt, long-te...